-- Every model step of a Conversation turn is durable product data: reply text,
-- tool calls and tool results. Streaming text is a draft until its step lands.
CREATE TABLE turn_steps (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id bigint NOT NULL REFERENCES turns ON DELETE CASCADE,
    attempt bigint NOT NULL,
    seq bigint NOT NULL,
    kind text NOT NULL CHECK (kind IN ('text','tool_use','tool_result')),
    content jsonb NOT NULL,
    at bigint NOT NULL DEFAULT extract(epoch FROM now())::bigint,
    UNIQUE (turn_id, attempt, seq)
);
CREATE INDEX turn_steps_turn ON turn_steps(turn_id, id);
ALTER TABLE turns ADD COLUMN draft text;
ALTER TABLE turns ADD COLUMN command text
    CHECK (command IS NULL OR length(btrim(command)) BETWEEN 1 AND 200);
ALTER TABLE turns ADD COLUMN created_at bigint NOT NULL DEFAULT extract(epoch FROM now())::bigint;
ALTER TABLE turns ADD COLUMN started_at bigint;
ALTER TABLE turns ADD COLUMN finished_at bigint;
