-- Phase 2 preserves the existing single-owner app data. Identity is explicit so
-- later membership work can scope the same records without rewriting IDs.
CREATE TABLE workspaces (id text PRIMARY KEY);
INSERT INTO workspaces VALUES ('local');
CREATE TABLE conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL DEFAULT 'local' REFERENCES workspaces,
    title text NOT NULL CHECK (length(btrim(title)) BETWEEN 1 AND 120),
    updated_at bigint NOT NULL DEFAULT extract(epoch FROM now())::bigint
);
CREATE TABLE turns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL REFERENCES conversations ON DELETE CASCADE,
    prompt text NOT NULL CHECK (length(btrim(prompt)) BETWEEN 1 AND 8000),
    response text,
    error text,
    state text NOT NULL CHECK (state IN ('queued','running','completed','failed')),
    model text,
    CHECK (state <> 'completed' OR response IS NOT NULL)
);
CREATE INDEX turns_conversation ON turns(conversation_id,id);
CREATE UNIQUE INDEX one_pending_turn ON turns(conversation_id) WHERE state IN ('queued','running');
CREATE TABLE todos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id text NOT NULL DEFAULT 'local' REFERENCES workspaces,
    title text NOT NULL CHECK(length(btrim(title)) BETWEEN 1 AND 500),
    completed boolean NOT NULL DEFAULT false
);
CREATE TABLE assistant_settings (
    workspace_id text NOT NULL DEFAULT 'local' REFERENCES workspaces,
    key text NOT NULL,
    value text NOT NULL,
    PRIMARY KEY(workspace_id,key)
);
CREATE TABLE command_receipts (
    operation_id text PRIMARY KEY,
    command jsonb NOT NULL,
    result_id bigint
);
CREATE TABLE legacy_imports (
    source text PRIMARY KEY,
    imported_at timestamptz NOT NULL DEFAULT now(),
    session jsonb
);
