use futures::future::BoxFuture;
use serde_json::Value;
use std::{collections::HashMap, sync::Arc};

/// Context handed to every tool call.
#[derive(Debug, Clone)]
pub struct ToolCtx {
    idempotency_key: String,
}

impl ToolCtx {
    /// Creates a context carrying the given idempotency key.
    pub fn new(idempotency_key: impl Into<String>) -> Self {
        Self {
            idempotency_key: idempotency_key.into(),
        }
    }

    /// Unique per tool call, identical on every retry of that call. Pass it to external
    /// systems (Stripe, email providers) so a retried call cannot double-apply.
    ///
    /// Shaped like `<run id>/t<turn>/c<index>`. Chosen by the engine, never by the model.
    pub fn idempotency_key(&self) -> &str {
        &self.idempotency_key
    }
}

/// Something the model can call. Usually generated by `#[tool]`.
pub trait Tool: Send + Sync + 'static {
    /// The tool's name, as the model refers to it.
    fn name(&self) -> &str;
    /// What the tool does, to help the model decide when to call it.
    fn description(&self) -> &str;
    /// JSON schema for the arguments object.
    fn schema(&self) -> Value;
    /// Whether calling twice with the same arguments and context is safe and gives the same
    /// result. Idempotent tools are retried on failure and double-called in tests; others are not.
    fn idempotent(&self) -> bool {
        true
    }
    /// Runs the tool with the model's arguments and resolves to its result.
    fn call(&self, ctx: ToolCtx, args: Value) -> BoxFuture<'static, Result<Value, ToolError>>;
}

/// Why a tool call failed.
#[derive(Debug, Clone, thiserror::Error)]
pub enum ToolError {
    #[error("invalid arguments: {0}")]
    /// The model's arguments did not match the tool's schema.
    InvalidArguments(String),
    #[error("{0}")]
    /// The tool ran and failed.
    Failed(String),
}

/// The tools available to an agent.
#[derive(Clone, Default)]
pub struct ToolSet {
    tools: HashMap<String, Arc<dyn Tool>>,
}

impl ToolSet {
    /// Adds a tool, replacing any existing tool with the same name.
    pub fn insert(&mut self, tool: impl Tool) {
        self.tools.insert(tool.name().to_owned(), Arc::new(tool));
    }

    /// The tool with this name, if there is one.
    pub fn get(&self, name: &str) -> Option<&Arc<dyn Tool>> {
        self.tools.get(name)
    }

    /// Every tool in the set, in no particular order.
    pub fn iter(&self) -> impl Iterator<Item = &Arc<dyn Tool>> {
        self.tools.values()
    }

    /// Whether the set has no tools.
    pub fn is_empty(&self) -> bool {
        self.tools.is_empty()
    }
}

impl std::fmt::Debug for ToolSet {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_list().entries(self.tools.keys()).finish()
    }
}
