#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE ROLE agentinc LOGIN PASSWORD 'agentinc';
CREATE ROLE temporal LOGIN PASSWORD 'temporal';
CREATE DATABASE agentinc_${AINC_DB_SUFFIX} OWNER agentinc;
CREATE DATABASE temporal_${AINC_DB_SUFFIX} OWNER temporal;
CREATE DATABASE visibility_${AINC_DB_SUFFIX} OWNER temporal;
REVOKE CONNECT ON DATABASE agentinc_${AINC_DB_SUFFIX} FROM PUBLIC;
REVOKE CONNECT ON DATABASE temporal_${AINC_DB_SUFFIX} FROM PUBLIC;
REVOKE CONNECT ON DATABASE visibility_${AINC_DB_SUFFIX} FROM PUBLIC;
SQL
