use futures::future::BoxFuture;
use serde_json::Value;
use std::{collections::HashMap, sync::Arc};

/// Something the model can call. Usually generated by `#[tool]`.
pub trait Tool: Send + Sync + 'static {
    fn name(&self) -> &str;
    fn description(&self) -> &str;
    /// JSON schema for the arguments object.
    fn schema(&self) -> Value;
    fn call(&self, args: Value) -> BoxFuture<'static, Result<Value, ToolError>>;
}

/// Why a tool call failed.
#[derive(Debug, Clone, thiserror::Error)]
pub enum ToolError {
    #[error("invalid arguments: {0}")]
    InvalidArguments(String),
    #[error("{0}")]
    Failed(String),
}

/// The tools available to an agent.
#[derive(Clone, Default)]
pub struct ToolSet {
    tools: HashMap<String, Arc<dyn Tool>>,
}

impl ToolSet {
    pub fn insert(&mut self, tool: impl Tool) {
        self.tools.insert(tool.name().to_owned(), Arc::new(tool));
    }

    pub fn get(&self, name: &str) -> Option<&Arc<dyn Tool>> {
        self.tools.get(name)
    }

    pub fn iter(&self) -> impl Iterator<Item = &Arc<dyn Tool>> {
        self.tools.values()
    }

    pub fn is_empty(&self) -> bool {
        self.tools.is_empty()
    }
}

impl std::fmt::Debug for ToolSet {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_list().entries(self.tools.keys()).finish()
    }
}
