// Generated by `cargo xtask generate` from api/openapi-3.0.json.
include!("generated.rs");

/// The generated operations call this before every request.
pub async fn client_header(request: &mut reqwest::Request) -> Result<(), std::convert::Infallible> {
    request.headers_mut().insert(
        "agent-inc-client",
        reqwest::header::HeaderValue::from_static(concat!(
            "ainc-client/",
            env!("CARGO_PKG_VERSION"),
            " (api 1)"
        )),
    );
    Ok(())
}
