// Run after opening the prototype: chrome-devtools-axi run < tests/preview-smoke.js
const assert=(condition,message)=>{if(!condition)throw new Error(message);};
await page.click('#main-nav [data-page="today"]');
await page.click('#reset-demo');
await page.click('[data-action="add-task"]');
await page.fill('#add-task-form input','A task added during the preview check');
await page.click('#add-task-form button[type="submit"]');
assert(await page.eval(()=>document.querySelector('.task-name').textContent==='A task added during the preview check'),'New task should appear immediately');
await page.click('.task-row input');
assert(await page.eval(()=>JSON.parse(localStorage.getItem('agentinc-preview-v1')).tasks[0].done),'Task completion should persist');
await page.click('#main-nav [data-page="tasks"]');
await page.click('[data-filter="done"]');
assert(await page.eval(()=>document.querySelector('#screen').textContent.includes('A task added during the preview check')),'Completed task should be findable');
await page.click('#main-nav [data-page="home"]');
await page.click('[data-scene="Morning"]');
assert(await page.eval(()=>document.querySelector('#brightness-output-0').textContent==='85%'),'Scene should update lights');
await page.click('[data-room="0"]');
assert(await page.eval(()=>document.querySelector('#brightness-0').disabled),'Off room should disable dimmer');
await page.click('[data-room="0"]');
await page.eval(()=>{const slider=document.querySelector('#brightness-0');slider.value='54';slider.dispatchEvent(new Event('input',{bubbles:true}));});
assert(await page.eval(()=>document.querySelector('#brightness-output-0').textContent==='54%'),'Dimmer should update readout');
await page.click('[data-action="play"]');
assert(await page.eval(()=>document.querySelector('[data-action="play"]').getAttribute('aria-label')==='Pause music'),'Music control should reflect state');
await page.click('#main-nav [data-page="agents"]');
await page.click('[data-action="review-agent"]');
assert(await page.eval(()=>document.querySelector('[data-action="review-agent"]').disabled),'Review action should resolve');
await page.click('[data-action="new-agent"]');
await page.fill('#agent-name','Reading helper');
await page.fill('#agent-instructions','Collect articles to read this weekend.');
await page.click('#agent-form button');
assert(await page.eval(()=>document.querySelector('.agent-detail').textContent.includes('Reading helper')),'New draft agent should open');
await page.click('#reset-demo');
assert(await page.eval(()=>document.querySelector('.agent-picker .selected')?.dataset.agent==='coder'&&document.querySelector('.agent-detail h2').textContent==='Hue scene sync'),'Reset after creating a draft must restore a matching selected row and detail');
await page.click('#main-nav [data-page="library"]');
await page.fill('#library-search input','coffee');
await page.click('#library-search button');
assert(await page.eval(()=>document.querySelectorAll('.photo-item').length===1),'Library search should filter');
await page.fill('#library-search input','no-match-xyz');
await page.click('#library-search button');
assert(await page.eval(()=>document.querySelector('#screen .empty').textContent.includes('No matches')),'No results should be explicit');
await page.click('#open-command');
await page.fill('#command-search','Evee');
await page.press('Enter');
await page.click('[data-prompt="What needs my attention?"]');
assert(await page.eval(()=>document.querySelectorAll('.chat-message').length===3),'Evee example should render a user message and response');
await page.fill('.chat-composer input','<img src=x onerror=alert(1)>');
await page.click('.chat-composer .send-button');
assert(await page.eval(()=>!document.querySelector('.chat-container img')),'User text must be escaped');
await page.click('#main-nav [data-page="calendar"]');
await page.click('[data-action="add-event"]');
await page.fill('#event-name','Design review');
await page.fill('#event-time','18:00');
await page.fill('#event-end','17:00');
await page.click('#save-event');
assert(await page.eval(()=>document.querySelector('#event-dialog').open&&document.querySelector('#event-error').textContent.includes('after')),'Invalid event duration should be explained');
await page.fill('#event-end','18:45');
await page.click('#save-event');
assert(await page.eval(()=>document.querySelector('#screen').textContent.includes('Design review')&&!document.querySelector('#event-dialog').open),'New event should appear and modal should close');
await page.eval(()=>[...document.querySelectorAll('.calendar-event')].find(e=>e.textContent.includes('Design review')).click());
await page.fill('#event-name','Updated design review');
await page.fill('#event-date','2026-09-25');
await page.click('#save-event');
assert(await page.eval(()=>JSON.parse(localStorage.getItem('agentinc-preview-v1')).events.some(e=>e.name==='Updated design review'&&e.date==='2026-09-25')),'Edit should update the existing event and date');
await page.click('[data-calendar-view="month"]');
assert(await page.eval(()=>document.querySelectorAll('.month-day').length===35&&document.querySelector('.month-grid').textContent.includes('Updated design review')),'Month view should show the same event');
await page.click('[data-calendar-move="1"]');
assert(await page.eval(()=>document.querySelector('.calendar-period h2').textContent==='October 2026'),'Month navigation should change the month');
await page.click('[data-action="calendar-today"]');
await page.click('[data-action="add-event"]');
await page.click('[data-action="cancel-event"]');
assert(await page.eval(()=>!document.querySelector('#event-dialog').open),'Cancel should close event dialog');
await page.click('#main-nav [data-page="home"]');
assert(await page.eval(()=>document.querySelector('#workspace-tabs .active [data-page="home"]')),'Navigating should activate the matching workspace tab');
await page.click('[data-close-tab="home"]');
assert(await page.eval(()=>!document.querySelector('#workspace-tabs [data-page="home"]')&&document.querySelector('#page-name').textContent!=='Home'),'Closing an active tab should select another space');
await page.click('#new-tab');
assert(await page.eval(()=>document.querySelector('.work-tab.active').textContent==='New tab'&&document.activeElement.id==='space-search'),'New tab should open a focused space picker');
await page.fill('#space-search','Calendar');
assert(await page.eval(()=>document.querySelectorAll('.space-result').length===1),'New tab picker should filter spaces');
await page.press('Enter');
assert(await page.eval(()=>document.querySelector('#page-name').textContent==='Calendar'&&!document.querySelector('[data-close-tab="new"]')),'Choosing a space should replace the blank tab');
await page.click('#new-tab');
await page.click('[data-close-tab="new"]');
assert(await page.eval(()=>document.querySelector('#workspace-tabs [data-page="calendar"]')),'Closing a blank tab should preserve other tabs');
const matrix=await page.eval(()=>{const results=[];for(const layout of ['quiet','control','focus']){document.querySelector('button[data-direction="'+layout+'"]').click();for(const id of ['today','tasks','agents','home','calendar','library','apps']){document.querySelector('#main-nav [data-page="'+id+'"]').click();results.push({layout,page:id,heading:document.querySelector('#screen h1')?.textContent,overflow:document.documentElement.scrollWidth>innerWidth});}}return results;});
assert(matrix.every(x=>x.heading&&!x.overflow),'Every page and direction should render without page overflow: '+JSON.stringify(matrix.filter(x=>!x.heading||x.overflow)));
await page.click('#reset-demo');
await page.click('button[data-direction="control"]');
await page.click('#main-nav [data-page="today"]');
console.log(JSON.stringify({passed:true,interactions:26,viewports:'current browser viewport',pageDirectionChecks:matrix.length}));
