[package]
name = "ainc-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "ainc"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.13", default-features = false, features = [
  "rustls-no-provider",
  "charset",
  "http2",
  "system-proxy",
  "json",
] }
rustls = { version = "0.23", default-features = false, features = [
  "ring",
  "std",
  "tls12",
  "logging",
] }
ainc-client = { path = "../ainc-client" }
ainc-identity = { path = "../ainc-identity" }
clap_complete = "4"
tempfile = "3"
uuid.workspace = true
anyhow.workspace = true
clap = { version = "4", features = ["derive", "string"] }
serde_json.workspace = true
schemars = "0.8"
serde.workspace = true
tokio.workspace = true

[dev-dependencies]
ainc-daemon = { path = "../ainc-daemon" }
axum = "0.8"
sqlx = { version = "0.8", features = ["postgres"] }
